services:
  mysql:
    image: mysql:latest
    container_name: mysql_login_php
    restart: unless-stopped
    ports:
      - "4306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: login
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_login_php
    restart: unless-stopped
    ports:
      - "8089:80"
volumes:
  mysqldata: