services:
  # Iniciar o serviço PHP com extensões necessárias
  php:
    build: .
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html

  # Iniciar o serviço Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" 
    volumes:
      # Mapear o diretório do código-fonte e o arquivo de configuração do Nginx
      - ./src:/var/www/html
      # Mapear o arquivo de configuração do Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: mysql_login_php
    restart: unless-stopped
    ports:
      - "4306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # Mapear scripts de inicialização do MySQL
      - ./scripts:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: login
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword

  phpmyadmin:
    depends_on:
      - mysql
    # use a stable tag to avoid intermittent corrupted 'latest' pulls
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: phpmyadmin_login_php
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_ABSOLUTE_URI: http://localhost:8080/phpmyadmin/

volumes:
  mysqldata: